spring.application.name=Job-Scheduler

// for connecting with database
spring.datasource.url = jdbc:postgresql://localhost:5432/job-scheduler
spring.datasource.username = postgres
spring.datasource.password = 9423403760
			
// to update the schema based on entity --> only used for development
spring.jpa.hibernate.ddl-auto = update
			
// to see the sql when jpa calls any query
spring.jpa.show-sql = true
			
// to see the sql in formated way
spring.jpa.properties.hibernate.format_sql = true
